### ISSUE TITLE
company-slime backend not appearing on company-backends

### ISSUE THREAD

**Issue by joca-bt** [anwyn/slime-company#11]
I'm having some issues making slime-company work. The backend does not appear on ```company-backends``` and I'm not getting proper completions.

Reproducing:

```init.el```:
```
(defconst +emacs-dir+ (expand-file-name (if load-file-name
                                            (file-name-directory load-file-name)
                                          "~/.emacs.d/")))

(defconst +packages-dir+ (concat +emacs-dir+ "packages/"))

(defconst +packages+ '(company slime slime-company))

(defun load-package (package)
  (unless (package-installed-p package)
    (package-refresh-contents)
    (package-install package))
  (require package))

(setq package-archives '(("melpa-stable" . "https://stable.melpa.org/packages/")
                         ("melpa" . "https://melpa.org/packages/")
                         ("gnu" . "https://elpa.gnu.org/packages/"))
      package-archive-priorities '(("melpa-stable" . 20)
                                   ("melpa" . 10)
                                   ("gnu" . 0))
      package-user-dir +packages-dir+
      package-enable-at-startup nil)
(package-initialize)

(mapc #'load-package +packages+)

(setq company-idle-delay nil)
(global-company-mode t)

(setq inferior-lisp-program "sbcl")
(slime-setup '(slime-fancy
               slime-banner
               slime-company
               slime-indentation))

(global-set-key (kbd "C-<SPC>") #'company-complete)
```

Load Emacs with ```emacs -q -l init.el```.

After load is finished do ```M-x slime```.

Go to the SLIME REPL window, then ```M-x eval-expression``` ```company-backends```. The company-slime backend does not appear there.

When trying to complete something, the options shown are from the other company backends. See the image below.

![error](https://user-images.githubusercontent.com/1297942/28470387-7a30ebd6-6e31-11e7-9638-7a73ed3f5408.png)

What am I doing wrong?

company 0.9.4
slime 2.19
slime-company 1.1

**Comment by anwyn** [comment]
Hello,

it is just a minor but not very obvious thing that causes it to fail.
You should not load slime-company explicitly. Slime loads it for you during (slime-setup). If it is already loaded, slime fails to initialize it correctly. 

There is also no need to call (global-company-mode) if you don't want it for other reasons. Slime-company will activate itself in all derived-modes of `slime-company-major-modes'.

**Comment by joca-bt** [comment]
Hmmm, shouldn't we try to fix that? ```require```ing packages is pretty usual.

**Comment by anwyn** [comment]
You'd need to either change slime or move the (provide 'slime-company) from into the on-load part of define-slime-contrib, both of which I'm hesitant.

If you insist on loading slime-company yourself, you need to call slime-company-init (which is defined by  the define-slime-contrib macro and automatically called by slime if it loads the contrib).
