### ISSUE TITLE
Complete symbol names immediately after package name

### ISSUE THREAD

**Issue by akater** [anwyn/slime-company#16]
After package name is completed, I'd like slime-company to immediately suggest further completion without calling it manually.

I tried the following:

```lisp
(defun my/special-completion (completion-string)
  (and (string-equal ":" (substring completion-string -1 nil))
       (company-complete)))
(setq slime-company-after-completion 'my/special-completion)
```
to no effect aside from the following error:

> Company: An error occurred in post-command
Company: frontend company-pseudo-tooltip-unless-just-one-frontend error "Company: backend nil error "Symbol’s function definition is void: nil" with args (annotation some-package:)" on command post-command

Debugger does show completions returned properly at some point but the company “widget” does not appear. Some information from debugger:

- `(company-manual-begin)` evaluates to seemingly correct completion data
- `(company--insert-candidate #("some-package:" 0 14 (score "214.79" flags "-------p")))` evaluates to `nil`
- `(company-complete)` evaluates to `company-complete-common`

I also tried `(company-begin-backend 'company-slime)` instead of `(company-complete)`, to the exact same results. Tried adding `(interactive)` declaration to `my/special-completion` with various options, more or less blindly (don't have much experience with it).

Maybe I call it the wrong way, or maybe this has to be implemented at a deeper level.

**Comment by anwyn** [comment]
Sorry, I did look briefly into it, but it seem company completion is just not meant to be called recursively from within itself. Because this is what you are doing if you invoke company-complete from the slime-company-after-completion hook.
Using company-completion-finished-hook also did not help and yielded the same error.

**Comment by akater** [comment]
I'll try to address this issue to https://github.com/company-mode/company-mode then. Please don't close this one for now.

**Comment by anwyn** [comment]
There may be another way to achieve the behaviour you are looking for. Set company-idle-delay to a small value (like the default 0.5 sec) and add company-complete-selection to the company-begin-commands list. This reopens the completion menu after completing the package name.
Side effect of this is, that for normal completions the completion menu also stays open if you select the candidate with RET. If you complete with SPACE, it will close as usual.
You could work around this by inserting a space after the completion if the completion does not end with a colon. Like so:

```emacs-lisp
(add-to-list 'company-begin-commands 'company-complete-selection)

 (defun my/special-completion (completion-string)
         (unless (string-equal ":" (substring completion-string -1 nil))
           (just-one-space)))

(setq slime-company-after-completion 'my/special-completion)
```

**Comment by akater** [comment]
Thank you, I'll try this. Didn't post to company-mode yet, as there's a quite a bunch of existing issues there to check for duplicates.

**Comment by anwyn** [comment]
Tell me how you like it, to help me decide if this should be in slime-company-just-one-space.

**Comment by akater** [comment]
Feels very smooth with default `company-idle-delay` of `0.5`. I'm sorry I can't see how this feature can be incorporated into slime-company-just-one-space. I remove the inserted space immediately in the body of `my/special-completion`:

**Comment by akater** [comment]
Thank you! I believe this issue can be closed. Unless company-mode introduces certain restrictions for `company-begin-commands`, this looks like a conclusive solution and not a hack.

**Comment by anwyn** [comment]
Silly condition indeed. It will never be true. But I'm glad you like the solution. I will alter slime-company-just-one-space, because I think it will never make sense to append a space after a colon. That you do not like it after non packages symbols does not invalidate this :)
