### ISSUE TITLE
Doesn't work without (require 'cl)

### ISSUE THREAD

**Issue by dikeert** [anwyn/slime-company#17]
Hello!
It seems it doesn't work when I try to use it with `use-package`. It looks like it's missing `(require 'cl)` even though it has this:

```lisp
(eval-when-compile
  (require 'cl))
```

**Comment by anwyn** [comment]
Perhaps you are loading the source file and have not already loaded 'cl ? Elisp libs should not load cl at runtime.

The following is part of my config and works:

    (use-package slime-company
      :after (slime company)
      :config (setq slime-company-completion 'fuzzy))

but this should not be necessary if you use customization. With MELPA slime-company should be in your load path so a simple

    (slime-setup '(slime-fancy slime-company))

is enough.
