### ISSUE TITLE
slime-company breaks on unmatched #\" in the output

### ISSUE THREAD

**Issue by phoe** [anwyn/slime-company#18]
![zrzut ekranu z 2019-01-04 23-23-11](https://user-images.githubusercontent.com/15045546/50714106-be37ee80-1077-11e9-8d2e-c9052410f93f.png)

I'd expect `(with` to show completions such as `with-open-file` and such.

Clearing the buffer temporarily fixes the issue.

(Mistakenly posted this in https://github.com/slime/slime/issues/482 previously.)

**Comment by anwyn** [comment]
Hallo Michał,

slime-company thinks it is in a string (as determined by the function `company-in-string-or-comment`) and does not try to complete. If you prefer it to work in strings and comments as well, please set or customize the flag `slime-company-complete-in-comments-and-strings`.

**Comment by phoe** [comment]
Hey @anwyn 

I understand why it does that, and I understand how I can customize that behavior; nonetheless, the current customization options are not enough for me to consider this to be a proper fix.

I think slime-company should start recognizing strings or comments only in the REPL prompt; in other words, only in the area between the end of `PETRI/TEST>` and either the beginning of the area where output is printed and values are returned, or the end of buffer. This would mean that stray quotation marks will not be processed as they are outside the region parsed by slime-company, and completion would work correctly.

**Comment by anwyn** [comment]
@phoe Say if this works for you.

BTW nice color theme in the screenshot. Which one is it?

**Comment by phoe** [comment]
zenburn!

Thanks, will check it now.

**Comment by phoe** [comment]
Yes, it works! Thanks a million. Please publish this version to MELPA.

**Comment by anwyn** [comment]
Fine. MELPA has already picked it up automatically.
