### ISSUE TITLE
error while fetching package description with ::

### ISSUE THREAD

**Issue by 3b** [anwyn/slime-company#22]
When completing `cl::` and similar, I get the following error:

```
The symbol following #: contains a package marker: "CL:"

  Line: 1, Column: 4, File-Position: 4
```

It appears to be from https://github.com/anwyn/slime-company/blob/master/slime-company.el#L254-L255 in `slime-company--doc-buffer `, which only strips one `:` from the candidate.

Changing it to 
```lisp
  (format "#:%s" (string-remove-suffix ":" (string-remove-suffix ":" candidate))
```
avoids the error, but presumably there is some better way to strip one or more `:` than calling `string-remove-suffix` twice

**Comment by anwyn** [comment]
Thx for the report, I'll look into it, as time permits.

**Comment by anwyn** [comment]
| presumably there is some better way to strip one or more : than calling string-remove-suffix twice

That may be, but I did not find it quickly, so I took the easy approach. As a bonus, package descriptions should now also work in quickhelp popups.
