### ISSUE TITLE
"Company: backend company-slime error..."

### ISSUE THREAD

**Issue by eatobin** [anwyn/slime-company#24]
Hello,

I'm using the Development branch of Spacemacs and since its last update installed `~/.emacs.d/elpa/develop/slime-company-20210121.2336/slime-company.el` (version 1.4?), I've been receiving these Messages:

`Company: An error occurred in auto-begin`
`Company: backend company-slime error "Symbol’s function definition is void: simple" with args (candidates ...)`

and slime-company has not been auto-completing.

Possibly connected to #23?

Reverting to `slime-company-20210119.1552` (version 1.3?) solves the problem and returns the expected behavior.

Thank you for your help.

**Comment by anwyn** [comment]
Hello, what Lisp are you using with slime? Do you have company-quickhelp or company-box enabled?

**Comment by eatobin** [comment]
Hi. I'm using SBCL and have not enabled either of the options you asked
about. I've installed the Spacemacs Common Lisp Layer (
https://develop.spacemacs.org/layers/+lang/common-lisp/README.html) and am
using it's defaults.

**Comment by byulparan** [comment]
same problem here(with 20210121.2336 on melpa).
 I revert to 20200424 version, then It's ok.

**Comment by anwyn** [comment]
Hmm, works here. What is your Emacs version? The 1.4 version relies on lexical binding rules, which is rather new (for Emacs).

**Comment by eatobin** [comment]
From emacs-version:

GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo
version 1.16.0) of 2020-11-30

**Comment by anwyn** [comment]
Got it. There was still an `ecase' form, without cl- prefix.

**Comment by eatobin** [comment]
Great! Thank you. And thank you for slime-company. :-)

**Comment by sakurawald** [comment]
Get the same problem. Upgrade the `slime-company` package solves this.
