### ISSUE TITLE
Completing package names

### ISSUE THREAD

**Issue by spaceotter** [anwyn/slime-company#5]
Maybe I'm doing something wrong, but, when I type the beginning of a package name like (cl- company mode does not help me complete the package name, no completions appear. It does provide completions once I type the semicolon after the complete package name. I can complete the package name with C-M-i (slime-complete-symbol).

**Comment by anwyn** [comment]
This is a known limitation. You are not doing anything wrong. Patches are welcome.

**Comment by spaceotter** [comment]
I'm pretty busy this week but I might have a look. Slime has fuzzy completion that works across packages, using that as the source would be ideal.

**Comment by anwyn** [comment]
Since 70313b73 you can use fuzzy completion too. This will complete package names.

**Comment by digikar99** [comment]
And may be, please make `slime-company-completion` more prominent - put it on README perhaps.. It took quite a bit of digging to discover how to enable fuzzy completion.
