### ISSUE TITLE
Fork `slime-fontify-string`from `slime-autodoc`

### ISSUE THREAD

**Issue by egarrulo** [anwyn/slime-company#6]
`slime-company` uses either `slime-fontify-string` or `slime-autodoc--fontify` from SLIME.  `slime-fontify-string` had been removed, albeit now the SLIME maintainers have kindly added it back, but deprecated.  `slime-autodoc--fontify` is a private function and could change without notice (see https://github.com/slime/slime/issues/249).  Since SLIME is in the public domain, it could make sense to just copy the code for `slime-fontify-string`, rename it, and maintain it separately.

Thanks for your attention.

**Comment by anwyn** [comment]
Thanks for the heads-up. After reading slime/slime#249 I am inclined to follow your proposal.
